server:
  port: 8083
spring:
  profiles:
    active: qa
  config:
    import: "optional:configserver:http://localhost:9999/"
  application:
    name: domaine
  datasource:
    #url: 'jdbc:h2:mem:domdb'
    url: jdbc:mysql://mysqldb:3306/testDocker?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  #h2:
  #  console:
  #    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
  eureka:
    client:
      service-url:
        defaultZone: 'http://localhost:8761/eureka/'
management:
  endpoints:
    web:
      exposure:
        include: "*"
#eureka:
 # instance:
   # prefer-ip-address: true
build:
  version: "1.0"
author:
  name: "sarra makhlouf"
  email: "smakhlouf278@gmail.com"


