services:
  mysqldb :
    image: mysql
    container_name: mysqldb
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testDocker

  domaine-ms:
    build: ./domaine-microservice
    container_name: domaine-ms
    ports:
      - "8084:8083"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/testDocker"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysqldb :
        condition: service_healthy